version: '3.8'

services:
  rivetqd:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - rivetq-data:/app/data
    environment:
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - rivetqd

volumes:
  rivetq-data:
